/**
 * Market Report PDF Generator — Creates white-label PDF market reports
 * Uses HTML-to-PDF approach compatible with Vercel serverless
 */

import type { MarketIndex, MarketReport } from "./types";

interface PDFBranding {
  agency_name: string;
  logo_url?: string | null;
  primary_color: string;
  contact_email?: string | null;
  contact_phone?: string | null;
}

const DEFAULT_BRANDING: PDFBranding = {
  agency_name: "PropertyPilot AI",
  primary_color: "#6366f1",
};

/**
 * Generate HTML content for the market report PDF.
 * In production, convert via Puppeteer/Playwright or a PDF API service.
 */
export function generateReportHTML(
  report: MarketReport,
  branding: PDFBranding = DEFAULT_BRANDING
): string {
  const FLAG: Record<string, string> = {
    IT: "🇮🇹", FR: "🇫🇷", ES: "🇪🇸", DE: "🇩🇪", UK: "🇬🇧", PT: "🇵🇹",
  };

  const indicesRows = (report.indices as unknown as MarketIndex[])
    .map((idx) => `
      <tr>
        <td style="padding:8px;border-bottom:1px solid #e2e8f0;font-weight:600">${idx.city}</td>
        <td style="padding:8px;border-bottom:1px solid #e2e8f0;text-align:right">€${idx.avg_price_sqm.toLocaleString()}</td>
        <td style="padding:8px;border-bottom:1px solid #e2e8f0;text-align:right;color:${idx.price_change_1m >= 0 ? "#22c55e" : "#ef4444"}">${idx.price_change_1m >= 0 ? "+" : ""}${idx.price_change_1m.toFixed(1)}%</td>
        <td style="padding:8px;border-bottom:1px solid #e2e8f0;text-align:right;color:${idx.price_change_1y >= 0 ? "#22c55e" : "#ef4444"}">${idx.price_change_1y >= 0 ? "+" : ""}${idx.price_change_1y.toFixed(1)}%</td>
        <td style="padding:8px;border-bottom:1px solid #e2e8f0;text-align:right">${idx.avg_days_on_market}d</td>
        <td style="padding:8px;border-bottom:1px solid #e2e8f0;text-align:center">${idx.inventory_level}</td>
      </tr>
    `)
    .join("");

  const highlightsList = (report.highlights as string[])
    .map((h) => `<li style="margin-bottom:6px">${h}</li>`)
    .join("");

  const recommendationsList = (report.recommendations as string[])
    .map((r) => `<li style="margin-bottom:6px">${r}</li>`)
    .join("");

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #1e293b; max-width: 800px; margin: 0 auto; padding: 40px; }
    .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 40px; padding-bottom: 20px; border-bottom: 3px solid ${branding.primary_color}; }
    .logo { font-size: 24px; font-weight: 800; color: ${branding.primary_color}; }
    .date { color: #64748b; font-size: 14px; }
    h1 { font-size: 28px; margin-bottom: 8px; }
    h2 { font-size: 20px; margin-top: 32px; margin-bottom: 16px; color: ${branding.primary_color}; }
    .summary { background: #f8fafc; border-radius: 12px; padding: 20px; margin-bottom: 24px; line-height: 1.6; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
    th { padding: 10px 8px; text-align: left; font-size: 12px; text-transform: uppercase; letter-spacing: 0.5px; color: #64748b; border-bottom: 2px solid #e2e8f0; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; color: #94a3b8; font-size: 12px; text-align: center; }
    ul { padding-left: 20px; line-height: 1.8; }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">${branding.agency_name}</div>
    <div class="date">${report.report_date}</div>
  </div>

  <h1>${FLAG[report.country] ?? ""} ${report.title}</h1>

  <div class="summary">${report.summary}</div>

  <h2>Market Indices by City</h2>
  <table>
    <thead>
      <tr>
        <th>City</th>
        <th style="text-align:right">€/m²</th>
        <th style="text-align:right">1M Change</th>
        <th style="text-align:right">1Y Change</th>
        <th style="text-align:right">Days on Market</th>
        <th style="text-align:center">Inventory</th>
      </tr>
    </thead>
    <tbody>${indicesRows}</tbody>
  </table>

  <h2>Key Highlights</h2>
  <ul>${highlightsList}</ul>

  <h2>Recommendations</h2>
  <ul>${recommendationsList}</ul>

  <div class="footer">
    <p>${branding.agency_name} • ${branding.contact_email ?? ""} • ${branding.contact_phone ?? ""}</p>
    <p>Generated by PropertyPilot AI — propertypilot-ai.vercel.app</p>
  </div>
</body>
</html>
  `.trim();
}
